apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" $ }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: /var/run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: external
          name: {{` '{{ ds.meta_data.hostname }}' `}}
      preKubeadmCommands:
      - hostname {{` "{{ ds.meta_data.hostname }}" `}}
      - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
      - echo "127.0.0.1   localhost" >>/etc/hosts
      - echo {{` "127.0.0.1   {{ ds.meta_data.hostname }}" `}} >>/etc/hosts
      - echo {{` "{{ ds.meta_data.hostname }}" `}} >/etc/hostname
      {{- if .Values.kubeadm.users }}
      {{- range .Values.kubeadm.users }}
      users:
      - name: {{ .name }}
        sshAuthorizedKeys:
        {{- range .authorizedKeys }}
        - {{ . }}
        {{- end }}
        sudo: ALL=(ALL) NOPASSWD:ALL
      {{- end }}
      {{- end }}
