apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VSphereCluster
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    {{- include "helm-keep" . | nindent 4 }}
spec:
  controlPlaneEndpoint:
    host: '{{ ((.Values.connectivity.network).controlPlaneEndpoint).host }}'
    port: {{ ((.Values.connectivity.network).controlPlaneEndpoint).port | default 6443 }}

  identityRef:
    kind: Secret
    name: {{ include "credentialSecretName" $ }}
  server: {{ .Values.vcenter.server }}
  thumbprint: {{ .Values.vcenter.thumbprint }}
